<a href="https://colab.research.google.com/github/YaninaTesta/Entrega-5-y-7/blob/main/Terminada_N5_Curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Programa Ingenias+ Data Science

# Ejercicios

1. Crear un arreglo de ceros de longitud 12
2. Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
3. Crear un arreglo que tenga los números del 10 al 49
4. Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
5. Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
6. Calcular la media de un arreglo usando np.sum
7. Calcular la varianza de un arreglo usando np.sum y np.mean
8. Crear un array de números aleatorios usando np.random.randn.


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [2]:
#Importar numpy
import numpy as np

In [3]:
array_ceros=np.zeros(12)
print(array_ceros)
len (array_ceros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [11]:
#Ejercicio 1: Crear un arreglo de ceros de longitud 12
Ejercicio1=np.zeros(12)
print(Ejercicio1)
len (Ejercicio1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


12

In [12]:
#prueba: arreglo de unos de longitud 5
prueba=np.ones(5)
print(prueba)

[1. 1. 1. 1. 1.]


In [13]:
#Ejercicio 2: Crear un arreglo de longitud 10 con ceros en todas sus posiciones y un 10 en la posición número 5
Ejercicio2=np.zeros(10)
Ejercicio2[4]=10
print(Ejercicio2)

[ 0.  0.  0.  0. 10.  0.  0.  0.  0.  0.]


In [16]:
#prueba 2: en el arreglo de unos, que la tercer posicion tenga un 7
prueba[3]=7
print(prueba)

[1. 1. 1. 7. 1.]


In [8]:
#Ejercicio 3: Crear un arreglo que tenga los números del 10 al 49
array_10_49=np.arange(10,50)
print(array_10_49)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
#Ejercicio 4: Crear una arreglo 2d de shape (3, 3) que tenga los números del 0 al 8
Ejercicio4=np.arange(9).reshape(3,3)
print(Ejercicio4)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [19]:
#Ejercicio 5: Crear un arreglo de números aleatorios de longitud 100 y obtener su media y varianza
Ejercicio5=np.random.rand(100)
print(Ejercicio5)
print("")
media = np.mean(Ejercicio5)
print("Media:", media)
print("")
varianza = np.var(Ejercicio5)
print("Varianza:", varianza)

[0.81521968 0.46387695 0.14752798 0.07142091 0.02583613 0.95950317
 0.38207436 0.61520436 0.08123976 0.78739713 0.22411066 0.1284551
 0.67514267 0.37941463 0.62496957 0.35287904 0.00651654 0.64679975
 0.59927394 0.40154106 0.51474049 0.71327947 0.98622858 0.85329045
 0.7215796  0.89898524 0.80693604 0.25700594 0.959918   0.78357853
 0.24029905 0.18220924 0.26637125 0.01667058 0.24773249 0.75363259
 0.30635014 0.65585347 0.06988726 0.86313099 0.59932052 0.20579819
 0.71814708 0.25476966 0.35888878 0.4309268  0.6089248  0.83299274
 0.81797391 0.78529631 0.46402963 0.77996229 0.70234479 0.95757798
 0.1133953  0.92728146 0.38328717 0.62347356 0.9212509  0.34602549
 0.71285954 0.56945808 0.89251733 0.86063928 0.66752862 0.08658465
 0.32531068 0.30326255 0.20815174 0.33602487 0.0755166  0.99511203
 0.50942581 0.72027183 0.26521644 0.90211629 0.75248884 0.84740008
 0.75114707 0.8425545  0.64244349 0.92063441 0.46677107 0.21798704
 0.88138833 0.42409867 0.91389202 0.67246302 0.46452355 0.18150

In [21]:
#pruba 5: crear arreglo de 25 numeros aleatorios y calcular media y varianza
Prueba5=np.random.rand(25)
print(Prueba5)
print("")
media25=np.mean(Prueba5)
print("Media:", media25 )
print("")
varianza25=np.var(Prueba5)
print("Varianza:", varianza25)

[0.84043608 0.19473259 0.26649538 0.81361877 0.58990788 0.93825496
 0.11207767 0.12877983 0.70708949 0.51544994 0.81134522 0.09057965
 0.0711154  0.63745698 0.37369331 0.41768557 0.86439988 0.77291976
 0.04112146 0.51034458 0.54874533 0.06222274 0.20613828 0.71638724
 0.13541833]

Media: 0.454656651544258

Varianza: 0.08841310566950186


In [24]:
#Ejercicio 6: Calcular la media de un arreglo usando np.sum
Ejercicio6 = np.sum(Ejercicio5)/[len(Ejercicio5)]
print(Ejercicio6)

[0.52954345]


In [26]:
#prueba6: Calcular la media de un arreglo usando np.sum
prueba6=np.sum(Prueba5)/[len(Prueba5)]
print(prueba6)

[0.45465665]


In [25]:
#ejercicio 7: Calcular la varianza de un arreglo usando np.sum y np.mean
Ejercicio7=np.sum((Ejercicio5-np.mean(Ejercicio5))**2)/[len(Ejercicio5)]
print(Ejercicio7)

[0.08222407]


In [27]:
#Ejercicio8
#Crear un array de números aleatorios usando np.random.randn

Ejercicio8=np.random.rand(15) #en mi caso elegi 15 numeros random
print(Ejercicio8)

[0.03498644 0.43515365 0.54150113 0.38269483 0.83561407 0.42326542
 0.49062878 0.77979908 0.93036649 0.33049057 0.75052048 0.69364878
 0.72445908 0.72010016 0.0862884 ]
